### ISSUE TITLE
Implement a query distribution equalizer

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#439] opened 2020-03-27 11:00 UTC
**Is your feature request related to a problem? Please describe:**  
All queries are generated equally right now.

**Please describe the solution you'd like:**  
To customize the generated workload, we would like to implement a query distribution equalizer. Similar to a sound equalizer we would be able to increase/decrease certain queries and customize workloads to individual needs.

**Affected Component(s):**  
`DatabaseManager`, `WorkloadGenerator`, `Frontend`

requested by @Bensk1

**Comment by fabianhe** [comment] 2020-03-27 11:11
Duplicate of #434, we should open a separate frontend issue once #434 is resolved.

**Closed by fabianhe** 2020-03-27 11:11 UTC
Labels: backend, duplicate, enhancement, frontend
