### ISSUE TITLE
Show historical performance data

### ISSUE THREAD

**Issue by cH3n7i** [hyrise/Cockpit#442] opened 2020-03-27 11:08 UTC
**Is your feature request related to a problem? Please describe:**  
When opening the performance vizualisations (throughput, latency) the graph starts at the current timestamp.

**Please describe the solution you'd like:**  
We collect the performance data in an ongoing manner, we should use the available data and visualize performance metrics that was measured in the past.

**Affected Component(s):**  
`Cockpit`, `Frontend`

**Comment by fabianhe** [comment] 2020-03-27 11:34
Duplicate of #264.

**Closed by fabianhe** 2020-03-27 11:34 UTC
Labels: Prio 1, backend, duplicate, enhancement, frontend
