### ISSUE TITLE
Hyrise crash when dropping tables

### ISSUE THREAD

**Issue by PeterTsayun** [hyrise/Cockpit#655] opened 2020-05-27 12:31 UTC
**Please describe the bug:**  
Hyrise crashes when trying to delete tables.

**Please describe steps to reproduce:**  
1. Start `hyriseServer` (branch `bp1920`)
2. Load `TPCH 0.1` tables
3. (Optional) execute `SELECT * FROM meta_tables;` to check the tables are loaded
4. execute `DROP TABLE customer_tpch_0_1;` in the `psql` console
5. `hyriseServer`: segmentation fault

**What is the expected behavior? Please describe:**  
Hyrise should delete tables.

**Affected Component(s):**  
`Hyrise`

**Additional context:**

**Comment by Bensk1** [comment] 2020-05-27 13:09
I will have a look

**Comment by Bensk1** [comment] 2020-05-27 13:28
I cannot reproduce it.

```
Jan.Kossmann=> COPY nation FROM '/home/Jan.Kossmann/hy/tpch_cached_tables/sf-0.010000/nation.bin';
SELECT 0
Jan.Kossmann=> COPY customer FROM '/home/Jan.Kossmann/hy/tpch_cached_tables/sf-0.010000/customer.bin';
SELECT 0
Jan.Kossmann=> SELECT * from meta_tables;
 table_name | column_count | row_count | chunk_count | target_chunk_size
------------+--------------+-----------+-------------+-------------------
 customer   |            8 |      1500 |           1 |             65535
 nation     |            4 |        25 |           1 |             65535
(2 rows)

Jan.Kossmann=> drop table customer;
 OK
----
(0 rows)
```

Did you rebuild the tables?

**Comment by PeterTsayun** [comment] 2020-05-27 13:43
> Did you rebuild the tables?

We built them about a week ago together with the `hyriseServer`. We'll rebuild them again and test one more time.

**Comment by PeterTsayun** [comment] 2020-05-27 16:05
> I cannot reproduce it.

With new tables, we still have a segmentation fault. Steps to reproduce:

1. Start hyriseServer (branch bp1920)
2. execute `COPY customer_tpch_0_1 FROM '/usr/local/hyrise/cached_tables/tpch_0_1/customer.bin';`
3. execute `DROP TABLE customer_tpch_0_1;`
4. execute `select * from meta_segments;` -> Segmentation fault

Instead of `meta_segments`, querying `meta_tables`, `meta_chunks` leads to the crash as well, whereas `meta_cached_queries` and `meta_cached_queries` work fine.

**Comment by Bensk1** [comment] 2020-05-27 16:08
Before you said that the segmentation fault occurs after dropping, now after selecting the meta table. That changes everything.

**Comment by PeterTsayun** [comment] 2020-05-27 16:16
> Before you said that the segmentation fault occurs after dropping, now after selecting the meta table. That changes everything.

The error occurred after dropping because it was registered by `DatabaseManager` and thus background jobs were querying meta information in the background, leading to the crash.

**Comment by Bensk1** [comment] 2020-05-27 16:29
Should be fixed in `bp1920`.

**Closed as completed** 2020-07-07 16:22 UTC
Labels: bug, backend
